#!/bin/bash

set -e
mkdir -p ssl
cd ssl

domain=$1
commonname=$domain
 
#Change to your company details
country=GB
state=London
locality=
organization="BBC TViPlayer"
organizationalunit=
email=email
 
password=dummy
 
if [ -z "$domain" ]
then
    echo "Argument not present."
    echo "Useage $0 [common name]"
 
    exit 99
fi
 
echo "Generating key request for $domain"
 
#Generate a key
openssl genrsa -des3 -passout pass:$password -out server.key 2048 -noout
 
#Remove passphrase from the key. Comment the line out to keep the passphrase
echo "Removing passphrase from key"
openssl rsa -in server.key -passin pass:$password -out server.key
 
#Create the request
echo "Creating CSR"
openssl req -new -key server.key -out server.csr \
    -subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email"

echo "Signing"
openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

echo "Done!"
 

